# For more information: https://laravel.com/docs/sail
version: '3.3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - ${PORT_PHP}:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel
networks:
  laravel:



